baseURL             = "https://ege.dev/"
languageCode        = "en-us"
title               = "ege.dev"
theme               = "sam"
pygmentsStyle       = "monokai"
pygmentsCodefences  = true

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "home"
    footerText           = "Ege Güneş - Software Engineer, Percona"

# Metadata for Open Graph and Twitter
    description          = "Ege's personal blog"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "ege.dev"
    # rss                = ""

[markup.goldmark.renderer]
    unsafe = true

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

[[params.mainMenu]]
    link = "/photography"
    text = "photography"

[[params.mainMenu]]
    link = "/writing"
    text = "writing"

[[params.mainMenu]]
    link = "/about"
    text = "about"

[imaging]
    quality = 75
