baseURL = "https://ege.dev/"
languageCode = "en-us"
title = "ege.dev"

[author]
  name = "Ege Güneş"
  homepage = "https://ege.dev/"
[params]
  description = "Ege's personal blog"
  githubUsername = "egegunes"
  linkedinusername = "egegunes"
  email = "egegunes@gmail.com"
  tagline = "Hi I'm Ege. Welcome to my blog."
[params.work]
  jobTitle = "DevOps Engineer"
  company = "Kartaca"
  companyUrl = "https://kartaca.com/"
[params.gpg]
  key = "0x505B97C85A1D0305"
  fingerprint = "C71C E137 EEC9 64E1 EA5C  365C 505B 97C8 5A1D 0305"
  link = "https://ege.dev/publickey.txt"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
