baseURL             = "https://ege.dev/"
languageCode        = "en-us"
title               = "ege.dev"
theme               = "weblog"
pygmentsStyle       = "monokai"
pygmentsCodefences  = true

[params]
    dateform        = "Mon Jan 02, 2006"
    dateformfull    = "Mon Jan 2 2006 15:04:05 -0700"
    favicon         = "sam.ico"
    homepage        = "home"
    footerText      = "Ege Güneş"
    description     = "Hello. I'm Ege." # Max 160 characters show in search results
    images          = ["tn.png"] # Image that shows on Twitter cards and Open Graph links to the site
    title           = "ege.dev"
    rss             = "ege.dev"
   	theme_toggle = false

[params.reply]
    text = "Reply to this post by sending an email to **egegunes [at] gmail [dot] com**."

[markup.goldmark.renderer]
    unsafe = true

[imaging]
    quality = 75

[permalinks]
	entries = "/entries/:year/:month/:slug/"

[pagination]
	pagerSize = 10

[[menu.main]]
	name = "NOW"
	weight = 1
	identifier = "now"
	url = "/now/"

[[menu.main]]
	name = "About"
	weight = 2
	identifier = "about"
	url = "/about/"

[[menu.main]]
	name = "Talks"
	weight = 3
	identifier = "talks"
	url = "/talks/"
