baseURL = "https://ege.dev/"
languageCode = "en-us"
title = "ege.dev"
theme = "solar-theme-hugo"
paginate = 10
pygmentsStyle = "solarized-dark"

[author]
  name = "Ege Güneş"
  homepage = "https://ege.dev/"
[params]
  scheme = "preference" # light, dark, gray or preference
  description = "Hi, I'm Ege. Welcome to my blog."

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[menu]
  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
  [[menu.main]]
    name = "GPG"
    url = "https://ege.dev/publickey.txt"
  [[menu.social]]
    name = "github.com/egegunes"
    url = "https://github.com/egegunes"
  [[menu.social]]
    name = "twitter.com/eomecon"
    url = "https://twitter.com/eomecon"
  [[menu.other]]
    name = "tecessus.com"
    url = "https://tecessus.com"
  [[menu.other]]
    name = "autosoteric.net"
    url = "https://autosoteric.net"
